ALTER TABLE restaurant
    ADD COLUMN description TEXT,
ADD COLUMN phone_number VARCHAR(20),
ADD COLUMN email VARCHAR(100),
ADD COLUMN opening_hours VARCHAR(100),
ADD COLUMN image_url VARCHAR(500),
ADD COLUMN deleted BOOLEAN DEFAULT FALSE,
ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

CREATE INDEX idx_restaurant_deleted ON restaurant(deleted);